include: "gitlab/ci_template.yml"

test manifest:
  variables:
    GIT_STRATEGY: fetch
  image: "$TEST_MANIFEST_IMAGE"
  stage: "preparation"
  script:
    - pytest-3 --junitxml=junit.xml --cov=build_manifest gitlab/build_manifest.py
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      junit:
        - "junit.xml"

test manifest amd64 docker:
  stage: "build docker"
  variables:
    REPO_SUFFIX: "$TEST_MANIFEST_AMD64_SUFFIX"
    TAG: "$TEST_MANIFEST_TAG-$GST_UPSTREAM_BRANCH"

    CONTEXT_DIR: "docker/test_manifest/"
    DOCKERFILE: "docker/test_manifest/Dockerfile"
  extends: .base
