variables:
  ###
  # IMPORTANT
  # These are the version tags for the docker images the CI runs against.
  # If you are hacking on them or need a them to rebuild, its enough
  # to change any part of the string of the image you want.
  ###
  FEDORA_TAG:  '2023-12-29.0'

  CHECKS_TAG: '2024-01-15.0'

  WINDOWS_TAG: '2023-12-29.0'
